py -m PyInstaller ^
  --noconfirm ^
  --clean ^
  --onedir ^
  --windowed ^
  --name "污染计数器v1.1.0" ^
  --icon "roco_counter_icon.ico" ^
  --add-data "paddleocr_models;paddleocr_models" ^
  --add-data "roco_counter_icon.ico;." ^
  --add-data "pollution_config.json;." ^
  --add-data "pollution_count.json;." ^
  --collect-all paddle ^
  --collect-all paddleocr ^
  --collect-all paddlex ^
  --exclude-module torch ^
  --exclude-module torchvision ^
  --exclude-module torchaudio ^
  --exclude-module tensorboard ^
  --exclude-module tensorflow ^
  --exclude-module jax ^
  --exclude-module jaxlib ^
  --exclude-module langchain ^
  --exclude-module langchain_core ^
  --exclude-module langchain_text_splitters ^
  --hidden-import imagesize ^
  --hidden-import pyclipper ^
  --hidden-import pypdfium2 ^
  --hidden-import bidi.algorithm ^
  --hidden-import shapely ^
  --hidden-import filelock ^
  --collect-all ruamel.yaml ^
  1.py
